### ISSUE TITLE
Sancionar a Guichu

### ISSUE THREAD

**Issue by melisa-abuin** [Reflej0/Sisa#1]

**Comment by Reflej0** [comment]
Hello Mel-A, the issue related to "Sancionar a Guichu" has been solved and will be available when our qualified professionals perform the minor update v2.6, we appreciate your comments, and suggestions.
**Closed Issue**

**Comment by JohnGalt17** [comment]
Melisa is the worst but you are the best.

sanctions rlz!

2018-02-07 11:51 GMT-03:00 Reflejo <notifications@github.com>:
